export * from './parameter-template.model';
export * from './test-catalog.model';
export * from './user-profile.model';
export * from './test-result.model';
export * from './test-schedule.model';
export * from './ai-report.model';
export * from './schedule-recommendation.model';
export * from './enums';
export * from './infrastructure/test-results.service'; 