name: CI

on:
  push:
    branches:
      - master
  pull_request:
  # Dodanie możliwości manualnego uruchomienia
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - run: npx playwright install --with-deps
      - uses: nrwl/nx-set-shas@v4

      # Testowanie modułu catalog
      - name: Test Catalog Module
        run: npx nx test catalog

      # Build głównej aplikacji my-health
      - name: Build Main Application
        run: npx nx build my-health

      # Lint dla affected projects
      - name: Lint Affected Projects
        run: npx nx affected -t lint
